module SignIn
  class CredentialLevel
    @requested_acr: untyped

    @credential_type: untyped

    @current_ial: untyped

    @max_ial: untyped

    @auto_uplevel: untyped

    include ActiveModel::Validations

    attr_reader requested_acr: untyped

    attr_reader current_ial: untyped

    attr_reader max_ial: untyped

    attr_reader credential_type: untyped

    attr_reader auto_uplevel: untyped

    def initialize: (requested_acr: untyped, credential_type: untyped, current_ial: untyped, max_ial: untyped, ?auto_uplevel: bool) -> void

    def can_uplevel_credential?: () -> untyped

    private

    def persisted?: () -> false

    def max_ial_greater_than_or_equal_to_current_ial: () -> (untyped | nil)
  end
end
