module SignIn
  class ServiceAccountAccessToken
    @uuid: untyped

    @service_account_id: untyped

    @user_attributes: untyped

    @user_identifier: untyped

    @scopes: untyped

    @audience: untyped

    @version: untyped

    @expiration_time: untyped

    @created_time: untyped

    @service_account_config: untyped

    include ActiveModel::Validations

    attr_reader uuid: untyped

    attr_reader service_account_id: untyped

    attr_reader audience: untyped

    attr_reader scopes: untyped

    attr_reader user_attributes: untyped

    attr_reader user_identifier: untyped

    attr_reader version: untyped

    attr_reader expiration_time: untyped

    attr_reader created_time: untyped

    # rubocop:disable Metrics/ParameterLists
    def initialize: (service_account_id: untyped, audience: untyped, user_identifier: untyped, ?scopes: untyped, ?user_attributes: ::Hash[untyped, untyped], ?uuid: untyped?, ?version: untyped?, ?expiration_time: untyped?, ?created_time: untyped?) -> void

    def persisted?: () -> false

    def to_s: () -> { uuid: untyped, service_account_id: untyped, user_attributes: untyped, user_identifier: untyped, scopes: untyped, audience: untyped, version: untyped, created_time: untyped, expiration_time: untyped }

    private

    def create_uuid: () -> untyped

    def set_expiration_time: () -> untyped

    def set_created_time: () -> untyped

    def validity_length: () -> untyped

    def service_account_config: () -> untyped
  end
end
