module SignIn
  class ValidatedCredential
    @user_verification: untyped

    @client_config: untyped

    @credential_email: untyped

    @user_attributes: untyped

    include ActiveModel::Validations

    attr_reader user_verification: untyped

    attr_reader credential_email: untyped

    attr_reader client_config: untyped

    attr_reader user_attributes: untyped

    def initialize: (user_verification: untyped, client_config: untyped, credential_email: untyped, user_attributes: untyped) -> void

    def persisted?: () -> false
  end
end
