class AccreditedIndividual < ApplicationRecord
  # Find all [AccreditedIndividuals] that are located within a distance of a specific location
  # @param long [Float] longitude of the location of interest
  # @param lat [Float] latitude of the location of interest
  # @param max_distance [Float] the maximum search distance in meters
  #
  # @return [AccreditedIndividual::ActiveRecord_Relation] an ActiveRecord_Relation of
  #   all individuals matching the search criteria
  def self.find_within_max_distance: (untyped long, untyped lat, ?untyped max_distance) -> untyped

  # return all poa_codes associated with the individual
  #
  # @return [Array<String>]
  def poa_codes: () -> untyped
end
