class EvssPPIUProvider
  @service: untyped

  include PPIUProvider

  def initialize: (untyped current_user) -> void

  def get_payment_information: (?untyped? _client_id, ?untyped? _rsa_key_path) -> untyped
end
