class SavedClaim::EducationBenefits::VA5495 < SavedClaim::EducationBenefits
  def after_submit: (untyped _user) -> (nil | untyped)

  private

  def send_confirmation_email: (untyped email) -> untyped
end
