module Preneeds
  # Models an Applicant from a {Preneeds::BurialForm} form
  #
  # @!attribute applicant_email
  #   @return [String] applicant's email
  # @!attribute applicant_phone_number
  #   @return [String] applicant's phone number
  # @!attribute applicant_relationship_to_claimant
  #   @return [String] applicant's relationship to claimant
  # @!attribute completing_reason
  #   @return [String] completing reason. Currently hard coded.
  # @!attribute mailing_address
  #   @return [Preneeds::Address] applicant's mailing address
  # @!attribute name
  #   @return [Preneeds::FullName] applicant's name
  #
  class Applicant < Preneeds::Base
    # (see Preneeds::BurialForm#as_eoas)
    #
    def as_eoas: () -> { applicantEmail: untyped, applicantPhoneNumber: untyped, applicantRelationshipToClaimant: untyped, completingReason: untyped, mailingAddress: untyped, name: untyped }

    # List of permitted params for use with Strong Parameters
    #
    # @return [Array] array of class attributes as symbols
    #
    def self.permitted_params: () -> ::Array[:applicant_email | :applicant_phone_number | :applicant_relationship_to_claimant | :completing_reason | { mailing_address: untyped, name: untyped }]
  end
end
