module Preneeds
  # Models a full name for persons included in a {Preneeds::BurialForm} form
  #
  # @!attribute first
  #   @return [String] first name
  # @!attribute last
  #   @return [String] last name
  # @!attribute maiden
  #   @return [String] maiden name
  # @!attribute middle
  #   @return [String] middle name
  # @!attribute suffix
  #   @return [String] name suffix
  #
  class FullName < Preneeds::Base
    # (see Preneeds::BurialForm#as_eoas)
    #
    def as_eoas: () -> untyped

    # (see Preneeds::Applicant.permitted_params)
    #
    def self.permitted_params: () -> ::Array[:first | :last | :maiden | :middle | :suffix]
  end
end
