module Preneeds
  # Models a veteran from a {Preneeds::BurialForm} form
  #
  # @!attribute date_of_birth
  #   @return [String] veteran's date of birth
  # @!attribute date_of_death
  #   @return [String] veteran's date of death
  # @!attribute gender
  #   @return [String] veteran's gender
  # @!attribute is_deceased
  #   @return [String] is veteran deceased? 'yes' or 'no'
  # @!attribute marital_status
  #   @return [String] veteran's marital status
  # @!attribute military_service_number
  #   @return [String] veteran's military service number
  # @!attribute place_of_birth
  #   @return [String] veteran's place of birth
  # @!attribute ssn
  #   @return [String] veteran's social security number
  # @!attribute va_claim_number
  #   @return [String] veteran's VA claim number
  # @!attribute military_status
  #   @return [String] veteran's military status
  # @!attribute address
  #   @return [Preneeds::Address] veteran's address
  # @!attribute current_name
  #   @return [Preneeds::FullName] veteran's current name
  # @!attribute service_name
  #   @return [Preneeds::FullName] veteran's name when serving
  # @!attribute service_records
  #   @return [Array<Preneeds::ServiceRecord>] veteran's service records
  #
  class Veteran < Preneeds::Base
    # (see Preneeds::BurialForm#as_eoas)
    #
    def as_eoas: () -> untyped

    # (see Preneeds::Applicant.permitted_params)
    #
    def self.permitted_params: () -> ::Array[:date_of_birth | :date_of_death | :gender | :is_deceased | :marital_status | :military_service_number | :place_of_birth | :ssn | :va_claim_number | :military_status | { race: untyped, address: untyped, current_name: untyped, service_name: untyped, service_records: ::Array[untyped] }]
  end
end
