class SavedClaim::Pension < CentralMailClaim
  FORM: "21P-527EZ"

  def regional_office: () -> ::Array["Department of Veteran Affairs" | "Pension Intake Center" | "P.O. Box 5365" | "Janesville, Wisconsin 53547-5365"]

  def attachment_keys: () -> ::Array[:files]

  def email: () -> untyped

  def send_confirmation_email: () -> (nil | untyped)

  # Send this Pension claim to the Lighthouse Benefit Intake API
  # https://developer.va.gov/explore/api/benefits-intake/docs
  # @see Lighthouse::PensionBenefitIntakeJob
  def upload_to_lighthouse: (?untyped? current_user) -> untyped
end
