module ExternalServicesRedis
  # Facade for the PagerDuty::ExternalServices::Service class.
  #
  class Status < Common::RedisStore
    @response: untyped

    include Common::CacheAside

    KEY: "pager_duty_services"

    # Returns either the cached response from the
    # PagerDuty::ExternalServices::Service.new.get_services call, or makes
    # a fresh call to that endpoint, then caches and returns the response.
    #
    # @return [PagerDuty::ExternalServices::Response] An instance of the
    #   PagerDuty::ExternalServices::Response class
    # @example ExternalServicesRedis.new.fetch_or_cache.as_json
    #   {
    #     "status"      => 200,
    #     "reported_at" => "2019-03-14T19:47:47.000Z",
    #     "statuses"    => [
    #       {
    #         "service"                 => "Appeals",
    #         "service_id"              => "appeals"
    #         "status"                  => "active",
    #         "last_incident_timestamp" => "2019-03-01T02:55:55.000-05:00"
    #       },
    #       ...
    #     ]
    #   }
    #
    def fetch_or_cache: () -> untyped

    # The HTTP status code from call to PagerDuty's API
    #
    # @return [Integer] For example, 200
    #
    def response_status: () -> untyped

    private

    def response_from_redis_or_service: () -> untyped
  end
end
