class EvssRatedDisabilitiesProvider
  @service: untyped

  include RatedDisabilitiesProvider

  def initialize: (untyped auth_headers) -> void

  # @param [string] _client_id: (unused) the lighthouse_client_id requested from Lighthouse
  # @param [string] _rsa_key_path: (unused) path to the private RSA key used to create the lighthouse_client_id
  def get_rated_disabilities: (?untyped? _client_id, ?untyped? _rsa_key_path) -> untyped

  def transform: (untyped data) -> untyped
end
