class LighthouseRatedDisabilitiesProvider
  @service: untyped

  @icn: untyped

  include RatedDisabilitiesProvider

  def initialize: (untyped icn) -> void

  # @param [string] lighthouse_client_id: the lighthouse_client_id requested from Lighthouse
  # @param [string] lighthouse_rsa_key_path: path to the private RSA key used to create the lighthouse_client_id
  # @return [integer] the combined disability rating
  def get_combined_disability_rating: (?untyped? lighthouse_client_id, ?untyped? lighthouse_rsa_key_path) -> untyped

  # @param [string] lighthouse_client_id: the lighthouse_client_id requested from Lighthouse
  # @param [string] lighthouse_rsa_key_path: path to the private RSA key used to create the lighthouse_client_id
  # @return [DisabilityCompensation::ApiProvider::RatedDisabilitiesResponse] a list of individual disability ratings
  def get_rated_disabilities: (?untyped? lighthouse_client_id, ?untyped? lighthouse_rsa_key_path) -> untyped

  # @param [string] lighthouse_client_id: the lighthouse_client_id requested from Lighthouse
  # @param [string] lighthouse_rsa_key_path: path to the private RSA key used to create the lighthouse_client_id
  def get_data: (?untyped? lighthouse_client_id, ?untyped? lighthouse_rsa_key_path) -> untyped

  def transform: (untyped data) -> untyped

  def decision_code_transform: (untyped decision_code_text) -> untyped
end
